### ISSUE TITLE
Vertical support

### ISSUE THREAD

**Issue by miguelocarvajal** [Taymindis/react-router-native-animate-stack#1]
This library seems just what I was looking for.

I do need vertical support so certain parts can be swiped vertically.

Any pointers on how I can implement this?

**Comment by Taymindis** [comment]
Hmm... I have only giving gestureX value for swiping customisation

[GestureX Value](https://github.com/Taymindis/react-router-native-animate-stack/blob/858e0d14f7c2a9beab774ed7c38a5f0f290f270f/src/AnimatedStack.tsx#L153)

If you said swiping from Bottom to Top, It will be an enhancement but not difficult to do, you just override my gesture constructor from X to Y will do. Or I will enhance it in this weekend.

If you want to navigate vertically please refer
[Vertical navigation](https://github.com/Taymindis/react-router-native-animate-stack/blob/master/README.md#transition-up-like-scaling)

**Comment by miguelocarvajal** [comment]
Sweet! I'll take a look.

Thanks for the quick response.

**Comment by Taymindis** [comment]
Hi @miguelocarvajal , 

The version 1.2.6 will have vertical swiping support, please take a look [this snippet](https://github.com/Taymindis/react-router-native-animate-stack#vertical-swipe-and-navigation) for more details
