### ISSUE TITLE
Working only the first time (Question unclear, example needed, Issue cannot replicate)

### ISSUE THREAD

**Issue by khrizt** [Taymindis/react-router-native-animate-stack#2]
Hi,

I'm trying to add this library to my app as it looks really great.

I just installed everything and replaced `Switch` with `AnimatedStack` and everything works ok I can go to a different URL and swipe back, but once I get back I have to double press items to view the screen of the new URL and swipe back does not work.

In my app we have 2 nested routes' switches, I was wondering if this could be the origin of the problem. If not and you think of something else, or some way to debug this behaviour, it'd be great.

Thanks and, once again, nice work!

**Comment by Taymindis** [comment]
the swipe back only workable when you have push route. I have never try 2 `AnimateStack` at the same time.

Would you mind to give me an example how to trigger this issue?

**Comment by khrizt** [comment]
I'll try and make an example repo to see if that happens outside my project. I'll keep you posted.

For the push part, does it mean that `goBack` from `react-router-native` won't work?

**Comment by Taymindis** [comment]
If push to next page, you will be able to swipe back(goBack), once swipeback(goBack), you will be able to swipe forward(goForward). 

if you push, you are able to goBack. It works as it is `react-router-native`

**Comment by khrizt** [comment]
Ok, thanks a lot for the clarification. I'll investigate some more and post the results.

**Comment by Taymindis** [comment]
Hi @khrizt , why not you just show me your mobile demo? How navigation wrong only first time?

**Comment by Taymindis** [comment]
@khrizt , if you are not able to make an example, could you show me your demo in gif only? I am awaiting your response

**Comment by khrizt** [comment]
Sorry, I know, last weeks have been kinda rough. Tomorrow I'll try to make the example.

**Comment by khrizt** [comment]
![ezgif-4-ae951577bd7b](https://user-images.githubusercontent.com/725227/82463119-b9cd7380-9abc-11ea-9e01-a22190aaf330.gif)

Ok, I managed to get the gif... I don't know why but it seems like it's doing a vertical animation. Also I'm getting the following warning. I'm working on doing an example from scratch so I can compare and see if there's something wrong with my project.

![Simulator Screen Shot - iPhone XS Max - 2020-05-20 at 17 04 02](https://user-images.githubusercontent.com/725227/82463192-ca7de980-9abc-11ea-971c-269233fbec49.png)

**Comment by Taymindis** [comment]
Please kindly update to latest version(1.2.9), it will fixed the warning and fixed the issue of default navigation not working for 2 times

[Demo](https://snack.expo.io/@minikawoon/react-router-native-animate-stack)

**Comment by khrizt** [comment]
Ok, sorry I didn't update to the latest version. With the latest I have managed this, I can swipe back but the transition entering a new route (even with the demo code) does not appear. For the navigation I'm doing `history.push(url);` could that be the problem?

![swipe-back](https://user-images.githubusercontent.com/725227/82536498-d911e280-9b48-11ea-899b-886fd1afe770.gif)

**EDIT:** I forgot to say, I have the code organized in a top-level switch that distributes the routes in different medium-level switches, could that be the problem as the top-level one is a switch and the other are `AnimatedStack`'s. If so, would you recommend me to join all routes in one file to have only one `AnimatedStack` or it can be done with multi-level switches.

**Comment by Taymindis** [comment]
I can't replicate what you said on my Demo, it's still animatable though, 

Based on what you said,  is your structure like this below ?
```jsx
<Switch> 
<Route render={props => (<AnimatedStack ....> <Route ..... ) } </


</Switch>
```

If `AnimatedStack` is under child switch, it wont be animated on parent route, only animatable inside child route itself.

If you click that row item, the parent should be `AnimatedStack` instead of `switch`

**Comment by Taymindis** [comment]
@khrizt  

I have aware some bug as it detected same parent wrongly, now It's fixed. Please kindly update version to 1.3.0. 

It will fixed your transition issue. However, `AnimatedStack` by default will skip nested route transition, but if you want to override it even nested route also animate, you can do like this below

```jsx
 const enterAnimKit = new Animated.Value(0);
  const width = useWindowDimensions().width;
  return (
    <SafeAreaView>
      <NativeRouter>
        <View style={styles.container}>
          <Navigator />
          <AnimatedStack
            swipeMethod={SwipeMethod.SWIPE_HORIZONTAL}
            swipeEdgeRange={0.15}
            swipeSuccessEdge={0.3}
            onMountAnimate={() => {
              Animated.timing(enterAnimKit, {
                toValue: 1,
                duration: 100
              }).start();
            }}
            onTransitionAnimate={({ location, action, isNestedRoute }) => {
             // if (isNestedRoute) return;  << Remove this one
              // Enter and exit or one only
              enterAnimKit.setValue(0);

              Animated.timing(enterAnimKit, {
                toValue: 1,
                duration: 200,
                delay: 0
              }).start();
            }}
            activedViewStyleHandler={({ location, action, isNestedRoute }) => {
              return {
                transform: [
                  {
                    translateX: enterAnimKit.interpolate({
                      inputRange: [0, 1],
                      outputRange: [width, 0]
                    })
                  }
                ]
              };
            }}
          >
...
...

</AnimatedStack>
```

**Comment by khrizt** [comment]
Wow, that's great. Thanks a lot, I'll try the new version. And about the nested routes, I'll try this solution but if you think it's better I can refactor the route structure so it does not have nested routes.

I'll keep you posted, and thanks again!!

**Comment by Taymindis** [comment]
It depends on your business structure, you do need nested route if your Mobile Apps has

MenuRoute,
MainPageRoute
LoginRoute
Other3rdPartyPageRoute

```jsx
<ParentRouteSwitch>
  <MenuRoute />
 <MainPageRoute>
     <NestedRouteStack>
             { Animation done at here only }
       </NestedRouteStack>
 </MainPageRoute>
 <LoginRoute {singlepageonly} />
</ParentRouteSwitch>

```

**Comment by khrizt** [comment]
Ok, new version works like a charm. Page transition and swipe back, ok. I've only tested child level routes. I'll try to find out the best way for my structure of nested routes. But it looks really cool now. Thanks a lot.

A couple of quick questions:

* Is it possible to change only the duration of the animation without having to implement a custom one?
* Would it be possible to do the transition backwards when using `goBack` method?
* Would it be possible to activate only the swipe part and deactivate transition animations? I'm just asking because maybe the product team only wants the swipe back part :man_shrugging:

Anyway thanks a lot, I'm gonna close the issue as it works awesomely well now.

**Comment by Taymindis** [comment]
@khrizt 

 1.  So far you need to custom your own transition to achieve the target.
 2. You also need to custom your own transition based on action param, 
```jsx


// - location: the react router native current targeted location
// - action: the react router native action, POP, PUSH, REPLACE
// - isNestedRoute: whether it's nested route in boolean type or location path are same, it's true as well
activedViewStyleHandler={({location, action, isNestedRoute}) => {
  if(action === 'PUSH')
    return {
     transform: [
                  {
                    translateX: enterAnimKit.interpolate({
                      inputRange: [0, 1],
                      outputRange: [width, 0]
                    })
                  }]
    };
   if(action === POP) {
  return {
     transform: [
                  {
                    translateX: enterAnimKit.interpolate({
                      inputRange: [0, 1],
                      outputRange: [0, width]
                    })
                  }]
    };


  }}


```


3. You just overrider 3 method and return ```{ }``` if i am not wrong you can try

**Comment by khrizt** [comment]
Great! Thanks again!

**Comment by Taymindis** [comment]
If you feel the customize code might felt too big of space of your coding style(if too many animation variation) , then you could wrap in HOC, name differently for you different variation animation, so your team might easy to use them :)
