### ISSUE TITLE
'useNativeDriver' was not specified

### ISSUE THREAD

**Issue by Dinkelborg** [Taymindis/react-router-native-animate-stack#3]
Just tried out your plugin but unfortunately with no success nothing animated the screens only change 
very laggy now and I get the warning message "Animated: 'useNativeDriver' was not specified. This is a required option and must be explicitly set to 'true' or 'false'

**Comment by Taymindis** [comment]
could you give me your example snippet so that I can see what is the issue?

**Comment by Taymindis** [comment]
Hi @Dinkelborg , you had solved the issue? I can't replicate your issue.

**Comment by spidi123q** [comment]
I am getting same issue

**Comment by spidi123q** [comment]
Raised a PR containing fix

**Comment by Taymindis** [comment]
Fixed with merged deployed to version 1.3.1
